name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist/

      # Используем v4 вместо v3
      - name: Store wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ matrix.python-version }}-wheels
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution
        run: python -m build --sdist

      # Используем v4 вместо v3
      - name: Store sdist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: dist/*.tar.gz

  publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aioabcpapi

    steps:
      # Используем v4 вместо v3
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: python-*-wheels
          path: dist/wheels
          merge-multiple: true

      # Используем v4 вместо v3
      - name: Download sdist artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-sdist
          path: dist/sdist

      - name: Prepare distribution directory
        run: |
          mkdir -p dist_final
          cp dist/wheels/*.whl dist_final/
          cp dist/sdist/*.tar.gz dist_final/
          ls -la dist_final/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist_final/