name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
          
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
          
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
          
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist
          
      - name: Upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz
  
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/aioabcpapi
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist
          
      - name: Prepare files for upload
        run: |
          mkdir -p final_dist
          cp dist/wheels/* final_dist/
          cp dist/sdist/* final_dist/
          
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: final_dist/