name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
          
      - name: Build wheels
        run: |
          python -m build --wheel
          
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-python-${{ matrix.python-version }}
          path: dist/*.whl
          
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          
      - name: Build sdist
        run: python -m build --sdist
        
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz
          
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]
    environment:
      name: pypi
      url: https://pypi.org/p/aioabcpapi
      
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist
          
      - name: Prepare files for upload
        run: |
          mkdir -p final_dist
          find dist -type f -name "*.whl" -o -name "*.tar.gz" | xargs -I {} cp {} final_dist/
          ls -la final_dist/
          
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: final_dist/